project:
  type: website
  output-dir: docs

website:
  title: "The Poldrack Lab at Stanford"
 
  navbar:
    left:
      - text: "Publications"
        href: publications
      - text: "Talks"
        href: talks
      - text: "Software"
        href: software

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



