name: Render quarto website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  render_site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install GDebi first
      run: sudo apt-get install gdebi-core
    - name: Download the deb file
      run: sudo curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb 
    - name: Install the deb file
      run: sudo apt-get install -y ./quarto-linux-amd64.deb
    - name: Verify Install
      run: /usr/local/bin/quarto check
    - name: Install academicdb
      run: pip install academicdb
    - name: decrypt config file
      run: ./decrypt_secret.sh
      env:
        CONFIG_SECRET_PASSPHRASE: ${{ secrets.CONFIG_SECRET_PASSPHRASE }}
    - name: build site
      run: quarto render .
